package mysql.entity;
// Generated Apr 11, 2016 9:21:47 AM by Hibernate Tools 3.6.0



/**
 * Balconista generated by hbm2java
 */
public class Balconista  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String username;
     private String password;

    public Balconista() {
    }

    public Balconista(String nome, String username, String password) {
       this.nome = nome;
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }


public String toString(){
    return "Nome:"+nome+"\nUsername:"+username;
}

}


