package mysql.entity;
// Generated Apr 15, 2016 12:13:02 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Balconista generated by hbm2java
 */
public class Balconista  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Date dataNascimento;
     private String morada;
     private int nuit;
     private String username;
     private String password;

    public Balconista() {
    }

	
    public Balconista(String nome, Date dataNascimento, int nuit, String username, String password) {
        this.nome = nome;
        this.dataNascimento = dataNascimento;
        this.nuit = nuit;
        this.username = username;
        this.password = password;
    }
    public Balconista(String nome, Date dataNascimento, String morada, int nuit, String username, String password) {
       this.nome = nome;
       this.dataNascimento = dataNascimento;
       this.morada = morada;
       this.nuit = nuit;
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getMorada() {
        return this.morada;
    }
    
    public void setMorada(String morada) {
        this.morada = morada;
    }
    public int getNuit() {
        return this.nuit;
    }
    
    public void setNuit(int nuit) {
        this.nuit = nuit;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }


public String toString(){
    return "Nome:"+nome+"\nUsername:"+username+"\nData de Nascimento"+dataNascimento;
}


}


