package mysql.entity;
// Generated Apr 26, 2016 2:12:35 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ItemPedido generated by hbm2java
 */
public class ItemPedido  implements java.io.Serializable {


     private Integer id;
     private Item item;
     private Pedido pedido;
     private Date data;

    public ItemPedido() {
    }

    public ItemPedido(Item item, Pedido pedido, Date data) {
       this.item = item;
       this.pedido = pedido;
       this.data = data;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


