package mysql.entity;
// Generated Apr 11, 2016 9:21:47 AM by Hibernate Tools 3.6.0



/**
 * Mesa generated by hbm2java
 */
public class Mesa  implements java.io.Serializable {


     private Integer id;
     private int numero;
     private boolean mesalivre;

    public Mesa() {
    }

    public Mesa(int numero, boolean mesalivre) {
       this.numero = numero;
       this.mesalivre = mesalivre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public boolean isMesalivre() {
        return this.mesalivre;
    }
    
    public void setMesalivre(boolean mesalivre) {
        this.mesalivre = mesalivre;
    }




}


