package mysql.entity;
// Generated Apr 15, 2016 12:13:02 AM by Hibernate Tools 3.6.0



/**
 * Tipoitem generated by hbm2java
 */
public class Tipoitem  implements java.io.Serializable {


     private Integer id;
     private String nome;

    public Tipoitem() {
    }

    public Tipoitem(String nome) {
       this.nome = nome;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


